# Generated by Django 5.0.4 on 2024-04-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbcore', '0006_remove_server_type_delete_database_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Server_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Database_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcore.database')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcore.port')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server_type'),
        ),
    ]
