# Generated by Django 4.2.11 on 2024-04-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dbcore", "0004_alter_database_server_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="database",
            name="type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dbcore.type"
            ),
        ),
        migrations.AlterField(
            model_name="database_server",
            name="port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dbcore.port"
            ),
        ),
        migrations.DeleteModel(
            name="Ports",
        ),
        migrations.DeleteModel(
            name="Types",
        ),
    ]
