# Generated by Django 5.0.4 on 2024-04-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0005_port_type_alter_database_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='type',
        ),
        migrations.DeleteModel(
            name='Database_server',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Server_type',
        ),
    ]
